# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: atomutil 0.1.5 ruby lib

Gem::Specification.new do |s|
  s.name = "atomutil".freeze
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["lyokato".freeze]
  s.date = "2018-09-04"
  s.description = "This library allows your to handle AtomPub and Atom Feed easily".freeze
  s.email = "lyo.kato@gmail.com".freeze
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "License.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "atomutil.gemspec",
    "lib/atomutil.rb",
    "spec/categories_spec.rb",
    "spec/category_spec.rb",
    "spec/content_spec.rb",
    "spec/customfeed_spec.rb",
    "spec/feed_spec.rb",
    "spec/link_spec.rb",
    "spec/namespace_spec.rb",
    "spec/opensearch_spec.rb",
    "spec/person_spec.rb",
    "spec/samples/feed.atom",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/threading_spec.rb"
  ]
  s.homepage = "http://github.com/lyokato/ruby-atomutil".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.6".freeze
  s.summary = "Ruby AtomPub Client".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>.freeze, ["< 11.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 2.4.0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.16.1"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    else
      s.add_dependency(%q<rake>.freeze, ["< 11.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 2.4.0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.16.1"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
    end
  else
    s.add_dependency(%q<rake>.freeze, ["< 11.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 2.4.0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.16.1"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.9"])
  end
end

